### ISSUE TITLE
ImportError: No module named 'pytz'

### ISSUE THREAD

**Issue by thomasleveil** [Zlitus/sublime-text-timestamp#2]
Hi,

Installation of this package did not work for me. In the sublime text console, I found :

```
reloading plugin Timestamp converter.timestampDecode
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "timestampDecode in C:\Users\tleveil\AppData\Roaming\Sublime Text 3\Installed Packages\Timestamp converter.sublime-package", line 1, in <module>
ImportError: No module named 'pytz'
```

**Comment by Zlitus** [comment]
Hello,

Really strange, my plugin don't use pytz since december 2017. I already saw this issue in the Sublime Text of a friend but work fine on many others. I'll investigate, thank you for the reporting.

Edit: Ok, I think it's because Sublime Text use the last tag of my project (And my last tag was not updated). I just created a new one, don't seem (yet) deployed. We will see if it's solve the issue in few hours…

**Comment by Zlitus** [comment]
Still don't solve the problem. Do you have any idea about how to force Sublime Text to update my package? Dind't find documentation for that (yet).

**Comment by thomasleveil** [comment]
from the [Package Control doc](https://packagecontrol.io/docs/submitting_a_package#Step_3)


> # 3. Decide how to Host
> You‘ll need to pick one of the following two hosting options:
> 
> Use a public GitHub or BitBucket repository. Only include one package per repository and be sure the root of the package is the root of the repository.
> Host .sublime-package files and a packages.json on a web server with SSL. For each release you‘ll need to **create and upload a new package file and update the packages.json information**. Hosting of the files must be done on a secure server to help ensure the security of users‘ machines. Unsecure URLs could lead to malicious code being loaded and run. This is rarely used – see example-repository.json for documentation.
> No matter how your package is hosted, Package Control will check it for updates approximately once per hour. The Last Seen date on the package detail page of this site will show the last time (UTC) when the package information was refreshed.
> 
> # 4. Pick a Versioning Strategy
> If you are using GitHub or BitBucket for your hosting, **you will need to create a tag each time you want to make a new version available to users**. The tag names must be a semantic version number.
> 
> Please note that branch-based releases have been deprecated and no new packages will be accepted that utilize that feature. Existing packages are encouraged to update to using tags.
> 
> If you chose manual package hosting, you will need to use semantic versioning in your packages.json file.

**Comment by MikhailKaduchka** [comment]
Didn't work for me either. Updated the content of package manually to latest version. 
`~/Library/Application Support/Sublime Text 3/Installed Packages/Timestamp converter.sublime-package` it's just a zip file.

**Comment by Unknow0059** [comment]
Issue still present.
Also, sure would be nice to get a Usage section in the readme and what kinds of strings the package accepts.

**Comment by Zlitus** [comment]
I finally found how to update the package 😅. Done 👍.
I'll add a Usage section in Readme too, thank @Unknow0059 for the tip.
