### ISSUE TITLE
how to use it? :-/

### ISSUE THREAD

**Issue by stefanocudini** [Zlitus/sublime-text-timestamp#3]

**Comment by Zlitus** [comment]
> 

Hello,
You can use it via the sublime text command panel by searching "Timestamp convert".

You can either convert dates to timestamp, or timestamps to date.

Here a quick video: https://youtu.be/BCcEfcSrVas

Please tell me if you have any issue

**Comment by adamlogan** [comment]
I watched the video, the associated commands (date2timestamp & timestamp2date) are not showing up for me on MacOS Big Sur w/ Sublime Text stable build 4113. Verified that the package was installed via package control by checking package control remove package (Timestamp Converter was listed), and I did see it in Installed Packages directory. So, I'm not sure what gives. I'm assuming something needs to change for this to work in Sublime Text 4.

**Comment by Zlitus** [comment]
No, it work fine on my ST4 stable build 4113, I do use it with this build & macOS.
I'll have a deep check on some virgin installation, but it should work fine.

Do you have any error on your ST console? You can open your console via the menu View -> Show Console.

**Comment by w0d** [comment]
ST console for ST4 build 4126 on Mint 20.1 gives

reloading python 3.3 plugin Timestamp converter.timestampDecode
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/x270/.config/sublime-text/Installed Packages/Timestamp converter.sublime-package/timestampDecode.py", line 1, in <module>
ImportError: No module named 'pytz'

**Comment by Zlitus** [comment]
Reply to @w0d removed message.

> ImportError: No module named 'pytz'

Well, I removed the dependency to pytz since 2017. I don't really understand why sometimes the Sublime Text Package is not updated. The update process of Sublime Text Packages is very unclear to me.

I could take some help, if somebody know how to proceed. I already read some of the docs, but it is still very unclear to me.

**Comment by Zlitus** [comment]
Issue should be fixed, please tell me if unclear 👍

**Comment by sergeevabc** [comment]
@Zlitus,
how do I convert 2022-0815-1745 (year-monthday-hoursmins) to 2022-08-15,
or perhaps such a conversion is out of the scope of your plugin?
